# Generated by Django 2.1.3 on 2019-03-21 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0003_auto_20190221_2240'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle_setting',
            unique_together={('login', 'type', 'info')},
        ),
    ]
