# Generated by Django 2.1.3 on 2019-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle_fuel_pos',
            options={'ordering': ['fuel_id', '-pos']},
        ),
        migrations.AddField(
            model_name='vehicle_fuel_pos',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Durchschnittsverbrauch', max_digits=10),
        ),
    ]
