# Generated by Django 2.1.3 on 2019-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20190221_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_fuel_pos',
            name='km',
            field=models.PositiveIntegerField(default=0, help_text='KM Stand'),
        ),
    ]
